<a href="https://colab.research.google.com/github/tah10mid/tahmid/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,4])
print(arr)
print(type(arr))

[1 2 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
myArr=np.zeros(5,dtype="int")
print(myArr)
print(myArr.size)

[0 0 0 0 0]
5


In [ ]:
import numpy as np
myArr=np.array([11,12,13,14])
print(myArr)

[11 12 13 14]


In [ ]:
newsize=myArr.size+1
myArr2=np.zeros(newsize,dtype="int")
for i in range(myArr.size):
  myArr2[i]=myArr[i]
myArr2[-1]=15
print(myArr2)

[11 12 13 14 15]


In [ ]:
for i in range(myArr2.size):
  print(i,myArr2[i])

0 11
1 12
2 13
3 14
4 15


In [ ]:
 length=int(input('Tell me the length first: '))
 myArr3=np.zeros(length,dtype="int")
 for i in range(length):
  val=int(input('Enter a value:'))
  myArr3[i]=val
print(myArr3)

Tell me the length first: 4
Enter a value:11
Enter a value:21
Enter a value:31
Enter a value:41
[11 21 31 41]


In [ ]:
length=int(input('Tell me the length first: '))
myArr3=np.zeros(length,dtype="int")
for i in range(length):
  val=int(input('Enter a value:'))
  myArr3[i]=val
  for x in range(myArray3.size):
   if myArr3[x]==11:
    print("peyechi")

Tell me the length first: 4
Enter a value:11


NameError: ignored

In [ ]:
array=np.array([10,3,20,1,6,5,11,2])
def selectionsort(arr):
  for i in range(arr.size):
    min_index=i
    for j in range((i+1),arr.size):
      if arr[j]<arr[min_index]:
        min_index=j
    temp=arr[i]
    arr[i]=arr[min_index]
    arr[min_index]=temp
  return arr
print(selectionsort(array))

[ 1  2  3  5  6 10 11 20]


In [ ]:
def bubbleSortAscending(arr):
    for i in range(arr.size-1):
        for j in range(arr.size-1-i):
            if arr[j+1] < arr[j]:
                # swapping
                temp = arr[j]
                arr[j] = arr[j+1]
                arr[j+1] = temp
    return arr

myArr = np.array([10,3,20,1,6,5,11,2])
print("Before Sorting:", myArr)

myArr = bubbleSortAscending(myArr)
print("After Sorting: ", myArr)

Before Sorting: [10  3 20  1  6  5 11  2]
After Sorting:  [ 1  2  3  5  6 10 11 20]


2D matrix

In [ ]:
import numpy as np
arr2D=np.zeros(shape=(3,3),dtype='int')
print(arr2D)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
mat1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("First row:",mat1[0])
print(mat1[2][1])
print("Row",mat1.shape[0])
print("column",mat1.shape[1])
print('Total',mat1.size)
print(len(mat1))
mat1[2][3]=20
print(mat1)

First row: [1 2 3 4]
10
Row 3
column 4
Total 12
3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 20]]


2d iterate

In [ ]:
mat2=np.array([[1,2,3,4],[5,6,7,8]])
rowL=mat2.shape[0]
colL=mat2.shape[1]
for r in range(rowL):
  for c in range(colL):
    print(mat2[r][c],end="")
  print()

1234
5678


In [ ]:
mat1=np.array([[1,3],[1,0],[1,2]])
mat2=np.array([[0,0],[7,5],[2,1]])
rowL=mat1.shape[0]
colL=mat1.shape[1]
mat3=np.zeros(shape=(mat1.shape[0],mat1.shape[1]),dtype="int")
for r in range(rowL):
  for c in range(colL):
      mat3[r][c]=mat1[r][c]+mat2[r][c]
print(mat3)



[[1 3]
 [8 5]
 [3 3]]


In [ ]:
mat1=np.array([[0,2,3],[1,1,0]])
rowL=mat1.shape[0]
colL=mat1.shape[1]
a=2
mat2=np.zeros(shape=(rowL,colL),dtype="int")
for r in range(rowL):
  for c in range(colL):
     mat2[r][c]=a*mat1[r][c]
print(mat2)

[[0 4 6]
 [2 2 0]]


In [ ]:
mat1=np.array([[0,5],[1,2],[3,4]])
mat2=np.array([[3,2,1],[1,2,4]])
mat1row=mat1.shape[0]
mat1col=mat1.shape[1]
mat2row=mat2.shape[0]
mat2col=mat2.shape[1]
mat3=np.zeros(shape=(mat1row,mat2col),dtype='int')
mat3row=mat3.shape[0]
mat3col=mat3.shape[1]
for r in range(mat3row):
  for c in range(mat3col):
    total=0
    for x in range(mat1col):
      total+=mat1[r][x]*mat2[x][c]
    mat3[r][c]=total
print(mat3)

[[ 5 10 20]
 [ 5  6  9]
 [13 14 19]]
